refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}:{m}{n}"

root:
  level: warn
  appenders:
    - stdout
loggers:
  lameboy:
    level: trace
